openapi: 3.0.0
info:
  title: Jota's finance
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /users/signup:
    post:
      tags:
        - default
      summary: Cadastro de usuário
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Heloise Ayla Figueiredo
                email: heloise_ayla_figueiredo@gmail.com
                password: XweEkD9Pmw
                role: ADMIN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/login:
    post:
      tags:
        - default
      summary: Fazer login usuário
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: heloise_ayla_figueiredo@gmail.com
                password: XweEkD9Pmw
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /goals:
    post:
      tags:
        - default
      summary: Cadastro de meta
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                description: Quarda dinheiro para o final do ano
                targetValue: '1500.00'
                startDate: 2025-04-01T12:00
                endDate: 2025-12-01T12:00
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/goals:
    get:
      tags:
        - default
      summary: Lista metas aparte do id do usuário
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /goals/3:
    put:
      tags:
        - default
      summary: Atualizar meta pelo id do usuário
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                targetValue: 15000
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete goal pelo id e usuário
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /bankAccounts:
    post:
      tags:
        - default
      summary: Criar conta bancaria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nameAccount: Conta Corrente Nubank
                typeAccount: DIGITAL_ACCOUNT
                openingBalance: 25000
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/bankAccount:
    get:
      tags:
        - default
      summary: Lista contas por usuario
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /bankAccounts/1:
    delete:
      tags:
        - default
      summary: Deletar conta bancaria de usuário
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /categorias:
    post:
      tags:
        - default
      summary: Cadastra categoria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Alimentação
                type: EXPENSE
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Lista categorias por usuários
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /categorias/1:
    delete:
      tags:
        - default
      summary: Deletar categoria
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /budgets:
    post:
      tags:
        - default
      summary: Cadastro de orçamento
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                valueBudget: 150
                monthYear: '2025-04-01'
                idCategory: 4
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Lista de orçamentos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /budgets/1:
    patch:
      tags:
        - default
      summary: Atualizar valor de orçamento
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                value: 200
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: Atualização de orçamento
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                valueBudget: 150
                monthYear: '2025-05-01'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Deleta orçamento
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /transactions:
    post:
      tags:
        - default
      summary: Transação
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                description: Compra de alimento
                transactionValue: 15
                typeTransaction: EXPENSE
                transactionDate: '2025-02-30T12:24:00'
                idCategory: 2
                idBankAccount: 2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Lista transações
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /transactions/1:
    delete:
      tags:
        - default
      summary: Deletar transição
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
